name: "CodeQL"

on:
 workflow_dispatch: # 手动选择分支触发
 # push:
 #   branches: 
     - main # 更新该分支的代码会触发codeql
#  schedule:
#     - cron: '0 14 * * *' # 这是需要写UTC时间，实际上会在北京时间运行每天晚上10点开始调度运行

jobs:
 analyze:
   name: Analyze
   runs-on: self-hosted
   permissions:
     actions: read
     contents: read
     security-events: write

   strategy:
     fail-fast: false
     matrix:
       language: [ 'typescript' ] # typescript 支持扫描分析.ts, .tsx, .mts, .cts后缀的文件

   steps:
   - name: Checkout repository
     uses: actions/checkout@v4

   - name: Initialize CodeQL
     uses: github/codeql-action/init@v3
     with:
       languages: ${{ matrix.language }}

   - name: Perform CodeQL Analysis
     uses: github/codeql-action/analyze@v3
     with:
       category: "/language:${{matrix.language}}"
